language: "en-us"
checkUpdate: true
economy:
  currencySymbol: "$"
  initialCurrency: 100
messages:
  join: "&6%player% joined the server."
  quit: "&6%player% left the server."
  welcome: "&dWelcome %player%, this is your first access to this server!"
regex:
  string: "^[a-zA-Z0-9_\u4e00-\u9fa5]+$"
  name: "^\w+$"
nameCheck: true
tpaCooldown: 60
mysql:
  enabled: false
  driver-class-name: "com.mysql.jdbc.Driver"
  jdbc-url: "jdbc:mysql://localhost:3306/mixtools"
  username: "root"
  password: "123456"
  properties:
    minimum-idle: 10
    idle-timeout: 30000
    maximum-pool-size: 20
    max-lifetime: 12000
    connection-timeout: 3000
trash:
  putThingSlots: [0,1,2,3,4,5,6,7,8,9,17,18,26,27,35]
  putThing: "LIME_STAINED_GLASS_PANE"
  line: 4