language: "en-us"
checkUpdate: true
economy:
  currencySymbol: "$"
  initialCurrency: 100
messages:
  join: "&7[&a+&7] %player%"
  quit: "&7[&c-&7] %player%"
  welcome: "&dWelcome %player%, this is your first access to this server!"
regex:
  string: "^[a-zA-Z0-9_]+$"
  name: "^[a-zA-Z0-9_]+$"
nameCheck: true
tpaExpireTime: 60
mysql:
  enabled: false
  driver-class-name: "com.mysql.jdbc.Driver"
  jdbc-url: "jdbc:mysql://localhost:3306/mixtools"
  username: "root"
  password: "123456"
  properties:
    minimum-idle: 10
    idle-timeout: 30000
    maximum-pool-size: 20
    max-lifetime: 12000
    connection-timeout: 3000
trash:
  putItemSlots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 17
    - 18
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
  item: "LIME_STAINED_GLASS_PANE"
  size: 36
  itemName: "&a"
  closeButton:
    enabled: false
    slot: 8
    item: "RED_STAINED_GLASS_PANE"
    name: "&cClose"
kit:
  itemInNonPlaceableSlots:
    type: "BLACK_STAINED_GLASS_PANE"
    name: "&a"
  editorCloseButton:
    item: "BARRIER"
    name: "&cClose and save"
motd:
  enabled: false
  icon: "example.png"
  players:
    changeCurrentPlayers: false
    currentPlayers: 20
    changeMaxPlayers: false
    maxPlayers: 20
    hidePlayers: false
  changeVersion: false
  version: "&a1.19.X"
  protocolVersion: auto
  string: "<green>Welcome to my server.</green><newline><blue>You can have a fun in this server!</blue>"
  Xmore:
    enabled: false
    x: 3
scoreboard:
  enabled: false
  changeDelay: 30
  scoreboards:
    example:
      - "&aExample Server"
      - "&aWelcome to my server"
      - "<green>You can use legacy color codes or MiniMessage format in scoreboards.</green>"
      - "&eExample server v1.0"
    papi:
      - "&aExample server"
      - "&eName: %player_name%"
      - "&cHealth: %player_health_rounded%"
      - "&bMoney: %vault_eco_balance%"