language: "en-us"
economy:
  currency-symbol: "$"
  maximum: 1.0E10
  initial-currency: 100
messages:
  join: "&6{player} joined the server."
  quit: "&6{player} left the server."
  welcome: "&dWelcome {player}, this is your first access to this server!"