name: MixTools
version: '${project.version}'
main: org.lins.mmmjjkx.mixtools.MixTools
api-version: 1.18
authors: [ mmmjjkx ]
description: An essential plugin like Essentials or CMI
softdepend: [PlaceholderAPI, Vault]
commands:
  mixtoolsreload:
    description: reload mixtools
    aliases: [mtlr]
  economy:
    description: economy system
    aliases: [eco,money]
  gamemode:
    description: change game mode
    aliases: [gm]
  kill:
    description: kill somebody or self
  killall:
    description: kill all players
  workbench:
    description: open workbench gui
    aliases: [wb]
  sudo:
    description: execute action by other player
  suicide:
    description: suicide
  back:
    description: return to the previous position
  commandgroup:
    description: command group
    aliases: [cg]
  home:
    description: back to homes
  delhome:
    description: delete home
  fly:
    description: fly
  itemlore:
    description: add item lore
  itemname:
    description: change item name
  sethome:
    description: set home
  setspawn:
    description: set spawn
  spawn:
    description: back to the spawn
  trash:
    description: open trash bin
  enderchest:
    description: open ender chest
    aliases: [ec]
  tpa:
    description: let you teleport to a player
  tpaaccept:
    description: accept teleport request
  tparefuse:
    description: refuse teleport request
  tpahere:
    description: let a player teleport to you
  teleport:
    description: teleport to some place
    aliases: [tp]
  serverinfo:
    description: get server info
  tpall:
    description: teleport all players to you
